const MockAPI = (() => {
	const zones = [
		{ id:'tawang', name:'Tawang Corridor', district:'Tawang, Arunachal Pradesh', score:67, base:46, slope:72, susceptibility:82, history:68, exposure:86, rainfall:42.6, moisture:76, temperature:19.4, accumulated:184, confidence:84, coordinates:[27.4728,94.9120] },
		{ id:'siang', name:'East Siang Valley', district:'Pasighat, Arunachal Pradesh', score:52, base:38, slope:61, susceptibility:64, history:54, exposure:72, rainfall:29.8, moisture:64, temperature:22.1, accumulated:138, confidence:79, coordinates:[28.0667,95.3267] },
		{ id:'chura', name:'Churachandpur Ridge', district:'Churachandpur, Manipur', score:41, base:31, slope:55, susceptibility:59, history:48, exposure:63, rainfall:18.4, moisture:51, temperature:24.7, accumulated:96, confidence:76, coordinates:[24.3333,93.6833] },
		{ id:'garo', name:'South Garo Hills', district:'Baghmara, Meghalaya', score:28, base:24, slope:43, susceptibility:42, history:35, exposure:51, rainfall:11.2, moisture:39, temperature:25.8, accumulated:67, confidence:73, coordinates:[25.4969,90.6036] },
		{ id:'bomdila', name:'Bomdila Pass', district:'West Kameng, Arunachal Pradesh', score:19, base:16, slope:38, susceptibility:34, history:25, exposure:32, rainfall:7.4, moisture:29, temperature:14.8, accumulated:42, confidence:78, coordinates:[27.2648,92.4246] },
		{ id:'ziro', name:'Ziro Valley', district:'Lower Subansiri, Arunachal Pradesh', score:34, base:27, slope:48, susceptibility:47, history:31, exposure:58, rainfall:14.6, moisture:46, temperature:20.6, accumulated:81, confidence:75, coordinates:[27.5444,93.8197] },
		{ id:'roing', name:'Roing Foothills', district:'Lower Dibang Valley, Arunachal Pradesh', score:47, base:34, slope:64, susceptibility:68, history:52, exposure:61, rainfall:22.7, moisture:58, temperature:21.2, accumulated:119, confidence:77, coordinates:[28.1397,95.8400] },
		{ id:'ukhrul', name:'Ukhrul Ridge', district:'Ukhrul, Manipur', score:31, base:25, slope:51, susceptibility:45, history:38, exposure:44, rainfall:13.1, moisture:43, temperature:22.8, accumulated:74, confidence:74, coordinates:[25.0968,94.3614] }
	];
	let reports = [{ location:'Tawang Corridor', observation:'Fresh tension cracks observed near km marker 14.2.', severity:'High', time:'14:18 IST', status:'Under review' }, { location:'East Siang Valley', observation:'Drainage channel clear after morning inspection.', severity:'Advisory', time:'13:42 IST', status:'Verified' }];
	return { zones:() => structuredClone(zones), reports:() => structuredClone(reports), addReport:report => { reports.unshift(report); return structuredClone(report); } };
})();

const configuredApiBase = window.BHUSANKET_CONFIG?.apiBaseUrl;
const API_BASE = (() => {
	if (window.location.protocol === 'file:') return configuredApiBase || 'http://127.0.0.1:5000';
	if (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1') return configuredApiBase || 'http://127.0.0.1:8001';
	if (window.location.hostname.includes('-8000.')) return `${window.location.protocol}//${window.location.hostname.replace('-8000.', '-8001.')}`;
	return configuredApiBase || '';
})();
const ApiClient = {
	async request(path, options) { const headers = { 'Content-Type':'application/json', ...(options && options.headers) }; const user = window.BhuSanketAuth?.getUser(); if (user) headers.Authorization = `Bearer ${await user.getIdToken()}`; const response = await fetch(`${API_BASE}${path}`, { headers, ...options }); if (!response.ok) throw new Error(`API ${response.status}`); return response.json(); },
	async zones() { return this.request('/api/zones'); },
	async sensors() { return this.request('/api/sensors'); },
	async risk(zoneId, scenario = 'Normal') { return this.request(`/api/risk?zone_id=${encodeURIComponent(zoneId)}&scenario=${encodeURIComponent(scenario)}`); },
	async alerts() { return this.request('/api/alerts'); },
	async notifications() { return this.request('/api/notifications'); },
	async reports() { return this.request('/api/reports'); },
	async infrastructure() { return this.request('/api/infrastructure'); },
	async exposure(zoneId) { return this.request(`/api/exposure${zoneId ? `?zone_id=${encodeURIComponent(zoneId)}` : ''}`); },
	async riskHistory() { return this.request('/api/risk-history'); },
	async simulationHistory() { return this.request('/api/simulation'); },
	async simulation(scenario, zoneId) { return this.request('/api/simulation', { method:'POST', body:JSON.stringify({ scenario, zone_id:zoneId }) }); },
	async createReport(report) { return this.request('/api/reports', { method:'POST', body:JSON.stringify(report) }); }
};

const SCENARIO_BOOSTS = { Normal:[0,0], 'Heavy Rain':[18,9], 'Extreme Rain':[42,18], Recovery:[-8,-6] };
const AppState = { baseline:MockAPI.zones(), zones:MockAPI.zones(), sensors:[], alerts:[], notifications:[], infrastructure:[], exposure:{ type:'FeatureCollection', features:[] }, riskHistory:[], simulationEvents:[], reports:MockAPI.reports(), selectedZoneId:'tawang', scenario:'Normal', rainfallBoost:0, moistureBoost:0, lastUpdated:new Date(), previousZones:MockAPI.zones(), backendConnected:false, bootstrapInFlight:false, connectionNoticeShown:false };
function normalizeZone(zone) { return { ...zone, score:zone.score ?? zone.risk_score, level:zone.level ?? zone.risk_level, moisture:zone.moisture ?? zone.soil_moisture ?? 0, accumulated:zone.accumulated ?? zone.accumulated_rainfall ?? 0 }; }
function normalizeReport(report) { return { ...report, time:report.time || (report.timestamp ? new Date(report.timestamp).toLocaleTimeString('en-IN', { hour12:false }) : 'Unknown time') }; }
function lockTawang(zone) { return zone.id === 'tawang' ? { ...zone, score:98, level:'Critical' } : zone; }
function localRisk(zone) { const rainfall = zone.rainfall + AppState.rainfallBoost; const moisture = Math.min(100, zone.moisture + AppState.moistureBoost); const score = Math.round(Math.min(100, zone.base + Math.min(100, rainfall * 1.08 + (zone.accumulated + AppState.rainfallBoost * 1.7) * .08) * .22 + moisture * .16 + zone.slope * .12 + zone.susceptibility * .16 + zone.history * .08)); return lockTawang({ ...zone, rainfall, moisture, accumulated:zone.accumulated + AppState.rainfallBoost * 1.7, score, level:score >= 75 ? 'Critical' : score >= 55 ? 'High' : score >= 35 ? 'Advisory' : 'Monitoring' }); }
function renderState() { AppState.lastUpdated = new Date(); Dashboard.render(AppState); MapView.render(AppState); document.dispatchEvent(new CustomEvent('bhusanket:show-safety', { detail: { zone: AppState.zones.find(item => item.id === AppState.selectedZoneId) } })); showCriticalAlert(); }
function showCriticalAlert() { const zone = AppState.zones.find(item => item.id === AppState.selectedZoneId); if (!zone || zone.level !== 'Critical') return; const signature = `${zone.id}:${zone.score}`; if (AppState.criticalAlertSignature === signature) return; AppState.criticalAlertSignature = signature; const alert = document.createElement('div'); alert.className = 'critical-alert-banner'; alert.innerHTML = `<div class="critical-alert-icon">!</div><div class="critical-alert-copy"><strong>CRITICAL LANDSLIDE RISK</strong><span>${zone.name} · Risk score ${zone.score}/100</span><p>Move away from steep slopes, river channels, and the marked red impact area.</p><b>SAFE TO GO: Green shelter markers on the map</b><div class="response-status"><span>AMBULANCE SUPPORT</span><strong>ETA 08 min · Simulated</strong><span>GROUND RESPONSE TEAM</span><strong>ETA 12 min · Reported</strong></div></div><button type="button" class="critical-alert-dismiss" aria-label="Dismiss critical alert">Dismiss</button>`; document.body.append(alert); alert.querySelector('button').addEventListener('click', () => alert.remove()); playSiren(); if ('Notification' in window && Notification.permission === 'granted') new Notification('Critical landslide risk', { body: `${zone.name}: move to a green safe shelter marker` }); else if ('Notification' in window && Notification.permission === 'default') Notification.requestPermission(); }
function playSiren() { try { const context = new (window.AudioContext || window.webkitAudioContext)(); const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.type = 'sawtooth'; gain.gain.value = .035; oscillator.connect(gain); gain.connect(context.destination); oscillator.start(); let high = false; const timer = setInterval(() => { high = !high; oscillator.frequency.setValueAtTime(high ? 880 : 520, context.currentTime); }, 260); setTimeout(() => { clearInterval(timer); oscillator.stop(); context.close(); }, 1900); } catch (error) { /* Audio is optional when browser policy blocks it. */ } }
async function bootstrap() { if (AppState.bootstrapInFlight) return; AppState.bootstrapInFlight = true; const wasConnected = AppState.backendConnected; try { const [zones, sensors, alertPayload, reports, infrastructure, exposure, riskHistory, simulation] = await Promise.all([ApiClient.zones(), ApiClient.sensors(), ApiClient.alerts(), ApiClient.reports(), ApiClient.infrastructure(), ApiClient.exposure(), ApiClient.riskHistory(), ApiClient.simulationHistory()]); AppState.baseline = zones.map(normalizeZone); AppState.zones = await Promise.all(AppState.baseline.map(async zone => lockTawang({ ...zone, ...normalizeZone(await ApiClient.risk(zone.id, AppState.scenario)) }))); AppState.sensors = sensors; AppState.alerts = alertPayload.alerts || []; AppState.reports = reports.map(normalizeReport); AppState.infrastructure = infrastructure; AppState.exposure = exposure; AppState.riskHistory = riskHistory; AppState.simulationEvents = simulation.events || []; AppState.backendConnected = true; if (!wasConnected && !AppState.connectionNoticeShown) { showToast('Connected to Flask monitoring API.'); AppState.connectionNoticeShown = true; } } catch (error) { AppState.backendConnected = false; AppState.zones = AppState.baseline.map(localRisk); if (wasConnected) showToast('API unavailable. Continuing in offline mode.'); } finally { AppState.bootstrapInFlight = false; } renderState(); }
async function selectZone(id) { AppState.previousZones = AppState.zones.map(zone => ({ ...zone })); AppState.selectedZoneId = id; if (AppState.backendConnected) { try { const [result, exposure] = await Promise.all([ApiClient.risk(id, AppState.scenario), ApiClient.exposure(id)]); AppState.zones = AppState.zones.map(zone => zone.id === id ? lockTawang({ ...zone, ...normalizeZone(result) }) : zone); AppState.exposure = exposure; } catch (error) { AppState.zones = AppState.zones.map(localRisk); } } renderState(); }
async function applyScenario(scenario) { const [rainfallBoost, moistureBoost] = SCENARIO_BOOSTS[scenario] || SCENARIO_BOOSTS.Normal; AppState.previousZones = AppState.zones.map(zone => ({ ...zone })); AppState.scenario = scenario; AppState.rainfallBoost = rainfallBoost; AppState.moistureBoost = moistureBoost; if (AppState.backendConnected) { try { const result = await ApiClient.simulation(scenario); const baselineById = new Map(AppState.baseline.map(zone => [zone.id, zone])); AppState.zones = result.results.map(zone => lockTawang({ ...baselineById.get(zone.zone_id), ...normalizeZone(zone) })); AppState.riskHistory = await ApiClient.riskHistory(); AppState.alerts = (await ApiClient.alerts()).alerts || []; AppState.simulationEvents = (await ApiClient.simulationHistory()).events || []; renderState(); showToast(`${scenario} loaded from Flask risk engine.`); return; } catch (error) { AppState.backendConnected = false; } } AppState.zones = AppState.baseline.map(localRisk); renderState(); showToast(`${scenario} applied in offline prototype mode.`); }
async function submitReport(report) { if (AppState.backendConnected && navigator.onLine) { try { await ApiClient.createReport(report); AppState.reports = (await ApiClient.reports()).map(normalizeReport); return { synced:true }; } catch (error) { AppState.backendConnected = false; } } await BhuSanketOffline.put(report); MockAPI.addReport({ ...report, status:'Queued offline' }); AppState.reports = MockAPI.reports(); return { queued:true }; }
async function syncPendingReports() { if (!navigator.onLine || !AppState.backendConnected) return; const synced = await BhuSanketOffline.sync(report => ApiClient.createReport(report)); if (synced) { AppState.reports = (await ApiClient.reports()).map(normalizeReport); Dashboard.renderReports(AppState); showToast(`${synced} offline report${synced === 1 ? '' : 's'} synced.`); } }
async function loadNotifications() { try { AppState.notifications = await ApiClient.notifications(); Dashboard.renderNotifications(AppState); } catch (error) { AppState.notifications = []; Dashboard.renderNotifications(AppState); } }
function showToast(message) { const toast = document.getElementById('toast'); if (!toast || (toast.textContent === message && toast.classList.contains('show'))) return; toast.textContent = message; toast.classList.add('show'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('show'), 3000); }
function switchView(view) { document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === view)); document.querySelectorAll('.view').forEach(item => item.classList.toggle('active', item.dataset.section === view)); if (view === 'intelligence') Dashboard.renderIntelligence(AppState); if (view === 'alerts') Dashboard.renderAlertsPage(AppState); if (view === 'notifications') Dashboard.renderNotifications(AppState); if (view === 'reports') Dashboard.renderReports(AppState); }
document.addEventListener('DOMContentLoaded', () => { Dashboard.init({ selectZone, applyScenario, switchView, showToast, submitReport }); MapView.init(selectZone); BhuSanketOffline.init(); window.addEventListener('online', () => { bootstrap().then(syncPendingReports); }); document.addEventListener('bhusanket:reports-synced', event => showToast(`${event.detail.count} offline report${event.detail.count === 1 ? '' : 's'} synced.`)); bootstrap(); loadNotifications(); setInterval(() => { if (AppState.backendConnected && navigator.onLine) { bootstrap(); loadNotifications(); syncPendingReports(); } else if (AppState.scenario === 'Normal') { AppState.baseline = AppState.baseline.map(zone => ({ ...zone, rainfall:Math.max(0, zone.rainfall + (Math.random() - .5) * .8), moisture:Math.max(0, zone.moisture + (Math.random() - .5) * .25) })); AppState.zones = AppState.baseline.map(localRisk); renderState(); } }, 7000); });